spring:
  datasource:
    url: jdbc:mysql://rm-bp17e966azq1889k8125130.mysql.rds.aliyuncs.com:3306/invoice_dbtest?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: invoice_tst
    password: Hdyy123@
    driver-class-name: com.mysql.cj.jdbc.Driver


    druid:
        aop-patterns: com.atguigu.admin.*  #监控SpringBean
        filters: stat,wall     # 底层开启功能，stat（sql监控），wall（防火墙）

        stat-view-servlet: # 配置监控页功能
          enabled: true
          login-username: admin
          login-password: admin
          resetEnable: false

        web-stat-filter: # 监控web
          enabled: true
          urlPattern: /*
          exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'


        filter:
          stat: # 对上面filters里面的stat的详细配置
            slow-sql-millis: 1000
            logSlowSql: true
            enabled: true
          wall:
            enabled: true
            config:
              drop-table-allow: false
  redis:

    host: 127.0.0.1
    port: 6379
    password: 123456
    client-type: jedis
    jedis:
       pool:
            max-active: 10




mybatis:
#  config-location: classpath:mybatis/mybatis-config.xml  #全局配置文件位置
#  mapper-locations: classpath:mybatis/mapper/*.xml  #sql映射文件位置
  configuration:
    map-underscore-to-camel-case: true


management:
  endpoints:
    enabled-by-default: true #暴露所有端点信息
    web:
      exposure:
        include: '*'  #以web方式暴露

  endpoint:
    health:
      show-details: always

